spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: farhantigadi123@gmail.com
    password: wyrw rnly jhue uxlr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: JournalApp
  profiles:
    active: dev

logging:
  level:
    com.EDigest.journalAPP: DEBUG       #for particular package with the annotation


#logging:
#  level:
#    root: ERROR   #for root level
#









